### PR TITLE
[Fix] Public key issue when update vscode via apt

### PR DESCRIPTION
**Pull request by doctor500**
Fix vscode update issue when update via the app from apt

### Problem

Screenshot_2023-09-12_01-42-52

### Solution
This problem can be fixed by renewing sign key. I adding additional steps to vscode installation script with script provided by vscode setup guide (see reference)
Screenshot_2023-09-12_01-44-10

### Reference
https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions

### CODE REVIEW

**Comment by phoenixbyrd** [comment]
Yea, installed and checked on my end, never seen that issue until now. Weird. Merged this.

**Comment by phoenixbyrd** [comment]
Actually no, this isn't working either still.

W: GPG error: http://packages.microsoft.com/repos/code stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
E: The repository 'http://packages.microsoft.com/repos/code stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by phoenixbyrd** [comment]
Couldn't get your method to work but found one that did. Should be resolved now.

**Comment by doctor500** [comment]
Hi again,
Wow that's awesome, thank you for helping fix it.

**Pull request merged**
